version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
      day: friday
    open-pull-requests-limit: 15

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
