linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - goerr113
    - nlreturn
    - paralleltest
    - tagalign
    - testpackage
    - wrapcheck
    - wsl

    # a bunch of templates are registered as unexported globals.
    - gochecknoglobals

    - deadcode  # deprecated (since v1.49.0)
    - exhaustivestruct  # deprecated (since v1.46.0)
    - golint  # deprecated (since v1.41.0)
    - ifshort  # deprecated (since v1.48.0)
    - interfacer  # deprecated (since v1.38.0)
    - maligned  # deprecated (since v1.38.0)
    - nosnakecase  # deprecated (since v1.48.1)
    - scopelint  # deprecated (since v1.39.0)
    - structcheck  # deprecated (since v1.49.0)
    - varcheck  # deprecated (since v1.49.0)

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - contextcheck
        - errorlint
        - funlen
        - gosec

linters-settings:
  varnamelen:
    max-distance: 15
    ignore-names:
      - tt  # Table tests
    ignore-decls:
      - wg sync.WaitGroup
