# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9  # frozen: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-yaml
      - id: check-json
        exclude: "^.vscode/"
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: rustfmt
        name: Check formatting
        entry: cargo fmt --
        language: system
        files: \.rs$

      - id: tests
        name: Run tests
        entry: cargo test
        language: system
        files: \.rs$
        pass_filenames: false

      - id: clippy
        name: Run clippy
        entry: cargo clippy -- -D warnings
        language: system
        files: \.rs$
        pass_filenames: false

  - repo: https://github.com/google/yamlfmt
    rev: c433f347693ee3bbbfd4f626e502685dd8aafa82  # frozen: v0.9.0
    hooks:
      - id: yamlfmt

  - repo: https://github.com/codespell-project/codespell
    rev: 355e50e14fd03fe83e4ed9aa0489824b150b3b58  # frozen: v2.2.5
    hooks:
      - id: codespell
